from setuptools import setup, find_packages

setup(name='ezNbeats',
      version='0.0',
      description='ezNbeats',
      url='na',
      author='stackaccount1',
      author_email='na',
      license='',
      packages=find_packages('src'),
      package_dir={'': 'src'},
      package_data={'ezNbeats': ['data/*.csv']},
      install_requires=[
          'sklearn~=0.0',
          'certifi~=2022.5.18.1',
          'charset-normalizer~=2.0.12',
          'cycler~=0.11.0',
          'fonttools~=4.33.3',
          'idna~=3.3',
          'joblib~=1.1.0',
          'kiwisolver~=1.4.2',
          'matplotlib~=3.4.3',
          'nbeats-forecast~=1.3.7',
          'nbeats-pytorch~=1.3.0',
          'numpy~=1.21',
          'packaging~=21.3',
          'pandas~=1.1.5',
          'Pillow~=9.1.1',
          'pyparsing~=3.0.9',
          'python-dateutil~=2.8.2',
          'pytz~=2022.1',
          'requests~=2.27.1',
          'scikit-learn~=1.1.1',  
          'scipy~=1.8.1',
          'six~=1.16.0',
          'sklearn~=0.0', 
          'threadpoolctl~=3.1.0',
          'torchvision~=0.12.0',
          'typing_extensions~=4.2.0',
          'urllib3~=1.26.9',],
      zip_safe=False)
      
     
