from setuptools import setup, find_packages

setup(name='ezNbeats',
      version='0.0',
      description='ezNbeats',
      url='na',
      author='stackaccount1',
      author_email='na',
      license='',
      packages=find_packages('src'),
      package_dir={'': 'src'},
      package_data={'ezNbeats': ['data/*.csv']},
      install_requires=[
          'sklearn~=0.0',
          'certifi~=2022.5.18.1',
          'charset-normalizer~=2.0.12',
          'cycler~=0.11.0',
          'idna',
          'joblib',
          'kiwisolver',
          'matplotlib',
          'nbeats-forecast',
          'nbeats-pytorch',
          'numpy',
          'packaging',
          'pandas',
          'Pillow',
          'pyparsing',
          'python-dateutil',
          'pytz',
          'requests',
          'scikit-learn',  
          'scipy',
          'six',
          'sklearn', 
          'threadpoolctl',
          'torchvision',
          'torch',],
      zip_safe=False)
      
     
